language: node_js
node_js: "12"
branches:
  only:
    - master
    - main
cache:
  directories:
    - node_modules
services:
  - mysql
before_install:
<<<<<<< HEAD
  - mysql -e 'CREATE DATABASE IF NOT EXISTS user_db;'
=======
  - mysql -e 'CREATE DATABASE IF NOT EXISTS user_db;'
>>>>>>> main
